// AUTO-GENERATED by scripts/gen-entry.js — do not edit by hand.
// Regenerate with `yarn build` (or `node scripts/gen-entry.js`) after refreshing ammo/.
// Runtime: bootstraps the WASM and re-exports the Ammo namespace as values.

// @ts-nocheck — ammo.wasm.js is the untyped emscripten bootstrap; types live in index.d.ts.
import wasm from './ammo.wasm.js';

// Locate the WASM binary next to this module. Vite fingerprints this and returns an absolute,
// route-independent URL — so hard-loading any deep route (e.g. /admin/chessboard) still finds it.
const wasmUrl = new URL('./ammo.wasm.wasm', import.meta.url).href;

// Resolve the runtime once via top-level await, so it is ready before any importer runs.
const lib = await wasm({ locateFile: (path) => (path.endsWith('.wasm') ? wasmUrl : path) });

// setEntityId/getEntityId attach an entity ID to a collision shape, so collision detection and
// raycasts can map a hit body back to the host engine's entity. (Native setUserPointer was tried
// and proved unreliable, so we patch a dedicated slot on the prototype.)
lib.btCollisionShape.prototype.setEntityId = function (id) { this._entityId = id; };
lib.btCollisionShape.prototype.getEntityId = function () { return this._entityId; };
lib.btPairCachingGhostObject.prototype.setEntityId = function (id) { this._entityId = id; };
lib.btPairCachingGhostObject.prototype.getEntityId = function () { return this._entityId; };

// --- classes ---
export const btIDebugDraw = lib.btIDebugDraw;
export const DebugDrawer = lib.DebugDrawer;
export const btVector3 = lib.btVector3;
export const btVector4 = lib.btVector4;
export const btQuadWord = lib.btQuadWord;
export const btQuaternion = lib.btQuaternion;
export const btMatrix3x3 = lib.btMatrix3x3;
export const btTransform = lib.btTransform;
export const btMotionState = lib.btMotionState;
export const MotionState = lib.MotionState;
export const btDefaultMotionState = lib.btDefaultMotionState;
export const btCollisionObject = lib.btCollisionObject;
export const btCollisionObjectWrapper = lib.btCollisionObjectWrapper;
export const RayResultCallback = lib.RayResultCallback;
export const ClosestRayResultCallback = lib.ClosestRayResultCallback;
export const btConstCollisionObjectArray = lib.btConstCollisionObjectArray;
export const btScalarArray = lib.btScalarArray;
export const AllHitsRayResultCallback = lib.AllHitsRayResultCallback;
export const btManifoldPoint = lib.btManifoldPoint;
export const ContactResultCallback = lib.ContactResultCallback;
export const ConcreteContactResultCallback = lib.ConcreteContactResultCallback;
export const LocalShapeInfo = lib.LocalShapeInfo;
export const LocalConvexResult = lib.LocalConvexResult;
export const ConvexResultCallback = lib.ConvexResultCallback;
export const ClosestConvexResultCallback = lib.ClosestConvexResultCallback;
export const btCollisionShape = lib.btCollisionShape;
export const btConvexShape = lib.btConvexShape;
export const btConvexTriangleMeshShape = lib.btConvexTriangleMeshShape;
export const btBoxShape = lib.btBoxShape;
export const btCapsuleShape = lib.btCapsuleShape;
export const btCapsuleShapeX = lib.btCapsuleShapeX;
export const btCapsuleShapeZ = lib.btCapsuleShapeZ;
export const btCylinderShape = lib.btCylinderShape;
export const btCylinderShapeX = lib.btCylinderShapeX;
export const btCylinderShapeZ = lib.btCylinderShapeZ;
export const btSphereShape = lib.btSphereShape;
export const btMultiSphereShape = lib.btMultiSphereShape;
export const btConeShape = lib.btConeShape;
export const btConeShapeX = lib.btConeShapeX;
export const btConeShapeZ = lib.btConeShapeZ;
export const btIntArray = lib.btIntArray;
export const btFace = lib.btFace;
export const btVector3Array = lib.btVector3Array;
export const btFaceArray = lib.btFaceArray;
export const btConvexPolyhedron = lib.btConvexPolyhedron;
export const btConvexHullShape = lib.btConvexHullShape;
export const btShapeHull = lib.btShapeHull;
export const btCompoundShape = lib.btCompoundShape;
export const btStridingMeshInterface = lib.btStridingMeshInterface;
export const btIndexedMesh = lib.btIndexedMesh;
export const btIndexedMeshArray = lib.btIndexedMeshArray;
export const btTriangleMesh = lib.btTriangleMesh;
export const btConcaveShape = lib.btConcaveShape;
export const btEmptyShape = lib.btEmptyShape;
export const btStaticPlaneShape = lib.btStaticPlaneShape;
export const btTriangleMeshShape = lib.btTriangleMeshShape;
export const btBvhTriangleMeshShape = lib.btBvhTriangleMeshShape;
export const btHeightfieldTerrainShape = lib.btHeightfieldTerrainShape;
export const btAABB = lib.btAABB;
export const btPrimitiveTriangle = lib.btPrimitiveTriangle;
export const btTriangleShapeEx = lib.btTriangleShapeEx;
export const btPrimitiveManagerBase = lib.btPrimitiveManagerBase;
export const btTetrahedronShapeEx = lib.btTetrahedronShapeEx;
export const btGImpactShapeInterface = lib.btGImpactShapeInterface;
export const CompoundPrimitiveManager = lib.CompoundPrimitiveManager;
export const btGImpactCompoundShape = lib.btGImpactCompoundShape;
export const TrimeshPrimitiveManager = lib.TrimeshPrimitiveManager;
export const btGImpactMeshShapePart = lib.btGImpactMeshShapePart;
export const btGImpactMeshShape = lib.btGImpactMeshShape;
export const btCollisionAlgorithmConstructionInfo = lib.btCollisionAlgorithmConstructionInfo;
export const btCollisionAlgorithm = lib.btCollisionAlgorithm;
export const btActivatingCollisionAlgorithm = lib.btActivatingCollisionAlgorithm;
export const btGImpactCollisionAlgorithm = lib.btGImpactCollisionAlgorithm;
export const btDefaultCollisionConstructionInfo = lib.btDefaultCollisionConstructionInfo;
export const btDefaultCollisionConfiguration = lib.btDefaultCollisionConfiguration;
export const btPersistentManifold = lib.btPersistentManifold;
export const btDispatcher = lib.btDispatcher;
export const btCollisionDispatcher = lib.btCollisionDispatcher;
export const btOverlappingPairCallback = lib.btOverlappingPairCallback;
export const btOverlappingPairCache = lib.btOverlappingPairCache;
export const btAxisSweep3 = lib.btAxisSweep3;
export const btBroadphaseInterface = lib.btBroadphaseInterface;
export const btCollisionConfiguration = lib.btCollisionConfiguration;
export const btDbvtBroadphase = lib.btDbvtBroadphase;
export const btBroadphaseProxy = lib.btBroadphaseProxy;
export const btRigidBodyConstructionInfo = lib.btRigidBodyConstructionInfo;
export const btRigidBody = lib.btRigidBody;
export const btConstraintSetting = lib.btConstraintSetting;
export const btTypedConstraint = lib.btTypedConstraint;
export const btPoint2PointConstraint = lib.btPoint2PointConstraint;
export const btGeneric6DofConstraint = lib.btGeneric6DofConstraint;
export const btGeneric6DofSpringConstraint = lib.btGeneric6DofSpringConstraint;
export const btSequentialImpulseConstraintSolver = lib.btSequentialImpulseConstraintSolver;
export const btConeTwistConstraint = lib.btConeTwistConstraint;
export const btHingeConstraint = lib.btHingeConstraint;
export const btSliderConstraint = lib.btSliderConstraint;
export const btFixedConstraint = lib.btFixedConstraint;
export const btConstraintSolver = lib.btConstraintSolver;
export const btDispatcherInfo = lib.btDispatcherInfo;
export const btCollisionWorld = lib.btCollisionWorld;
export const btContactSolverInfo = lib.btContactSolverInfo;
export const btDynamicsWorld = lib.btDynamicsWorld;
export const btDiscreteDynamicsWorld = lib.btDiscreteDynamicsWorld;
export const btVehicleTuning = lib.btVehicleTuning;
export const btVehicleRaycasterResult = lib.btVehicleRaycasterResult;
export const btVehicleRaycaster = lib.btVehicleRaycaster;
export const btDefaultVehicleRaycaster = lib.btDefaultVehicleRaycaster;
export const RaycastInfo = lib.RaycastInfo;
export const btWheelInfoConstructionInfo = lib.btWheelInfoConstructionInfo;
export const btWheelInfo = lib.btWheelInfo;
export const btActionInterface = lib.btActionInterface;
export const btKinematicCharacterController = lib.btKinematicCharacterController;
export const btRaycastVehicle = lib.btRaycastVehicle;
export const btGhostObject = lib.btGhostObject;
export const btPairCachingGhostObject = lib.btPairCachingGhostObject;
export const btGhostPairCallback = lib.btGhostPairCallback;
export const btSoftBodyWorldInfo = lib.btSoftBodyWorldInfo;
export const Face = lib.Face;
export const tFaceArray = lib.tFaceArray;
export const Node = lib.Node;
export const tNodeArray = lib.tNodeArray;
export const Material = lib.Material;
export const tMaterialArray = lib.tMaterialArray;
export const Anchor = lib.Anchor;
export const tAnchorArray = lib.tAnchorArray;
export const Config = lib.Config;
export const btSoftBody = lib.btSoftBody;
export const btSoftBodyRigidBodyCollisionConfiguration = lib.btSoftBodyRigidBodyCollisionConfiguration;
export const btSoftBodySolver = lib.btSoftBodySolver;
export const btDefaultSoftBodySolver = lib.btDefaultSoftBodySolver;
export const btSoftBodyArray = lib.btSoftBodyArray;
export const btSoftRigidDynamicsWorld = lib.btSoftRigidDynamicsWorld;
export const btSoftBodyHelpers = lib.btSoftBodyHelpers;

// --- enums ---
export const PHY_ScalarType = lib.PHY_ScalarType;
export const eGIMPACT_SHAPE_TYPE = lib.eGIMPACT_SHAPE_TYPE;
export const btConstraintParams = lib.btConstraintParams;

// --- functions ---
export const destroy = lib.destroy;

// --- runtime helpers (embind/emscripten) ---
export const castObject = lib.castObject;
export const wrapPointer = lib.wrapPointer;
export const getPointer = lib.getPointer;
