// Generates the package entry — a THREE-like single `Ammo` namespace over the WASM build —
// from the generated ammo/ammo.d.ts. Run after `download` + `patch:wasm` + `generate:module`:
//
//   node scripts/gen-entry.js
//
// It reads the class/enum/function names from ammo/ammo.d.ts and emits TWO committed files so
// consumers can `import * as Ammo from 'ammojs-typed'` and use `Ammo.btVector3` as BOTH a value
// (constructor) and a type — exactly like `import * as THREE from 'three'`:
//
//   ammo/index.js    runtime ESM: bootstraps the WASM (top-level await) and re-exports each
//                    class/enum/function as a value from the loaded instance.
//   ammo/index.d.ts  types: re-exports each name as a value (`export const X: typeof Ammo.X`)
//                    AND a type (`export type X = Ammo.X`). TS keeps the value and type
//                    namespaces separate, so one identifier serves both roles.
//
// The WASM binary is located via `new URL('./ammo.wasm.wasm', import.meta.url)`, so the bundler
// (Vite) fingerprints it and resolves it to an absolute URL independent of the page route — no
// `locateFile: '/' + p` hack and no static-copy step needed in the consumer.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const dtsPath = join(here, '../ammo/ammo.d.ts');
const dts = readFileSync(dtsPath, 'utf8');

// Top-level members of `declare module Ammo { ... }` are at 4-space indent.
const names = (kind) =>
  [...dts.matchAll(new RegExp(`^    ${kind} ([A-Za-z0-9_]+)`, 'gm'))].map((m) => m[1]);

const classes = names('class');
const enums = names('enum');
const functions = names('function');

// Runtime embind/emscripten helpers the generated .d.ts doesn't declare but the loaded instance
// exposes. Typed loosely (`any`), matching their dynamic nature.
const helpers = ['castObject', 'wrapPointer', 'getPointer'];

const banner = (gen) => `// AUTO-GENERATED by scripts/gen-entry.js — do not edit by hand.
// Regenerate with \`yarn build\` (or \`node scripts/gen-entry.js\`) after refreshing ammo/.
// ${gen}
`;

// --- ammo/index.js (runtime values + bootstrap) ---
const js = `${banner('Runtime: bootstraps the WASM and re-exports the Ammo namespace as values.')}
// @ts-nocheck — ammo.wasm.js is the untyped emscripten bootstrap; types live in index.d.ts.
import wasm from './ammo.wasm.js';

// Locate the WASM binary next to this module. Vite fingerprints this and returns an absolute,
// route-independent URL — so hard-loading any deep route (e.g. /admin/chessboard) still finds it.
const wasmUrl = new URL('./ammo.wasm.wasm', import.meta.url).href;

// Resolve the runtime once via top-level await, so it is ready before any importer runs.
const lib = await wasm({ locateFile: (path) => (path.endsWith('.wasm') ? wasmUrl : path) });

// setEntityId/getEntityId attach an entity ID to a collision shape, so collision detection and
// raycasts can map a hit body back to the host engine's entity. (Native setUserPointer was tried
// and proved unreliable, so we patch a dedicated slot on the prototype.)
lib.btCollisionShape.prototype.setEntityId = function (id) { this._entityId = id; };
lib.btCollisionShape.prototype.getEntityId = function () { return this._entityId; };
lib.btPairCachingGhostObject.prototype.setEntityId = function (id) { this._entityId = id; };
lib.btPairCachingGhostObject.prototype.getEntityId = function () { return this._entityId; };

// --- classes ---
${classes.map((n) => `export const ${n} = lib.${n};`).join('\n')}

// --- enums ---
${enums.map((n) => `export const ${n} = lib.${n};`).join('\n')}

// --- functions ---
${functions.map((n) => `export const ${n} = lib.${n};`).join('\n')}

// --- runtime helpers (embind/emscripten) ---
${helpers.map((n) => `export const ${n} = lib.${n};`).join('\n')}
`;

// --- ammo/index.d.ts (value + type under one name) ---
const valueAndType = (n) =>
  `export declare const ${n}: typeof Ammo.${n};\nexport type ${n} = Ammo.${n};`;

const dtsOut = `${banner('Types: each name is re-exported as both a value and a type.')}
import type Ammo from './ammo';

// --- classes (value + type) ---
${classes.map(valueAndType).join('\n')}

// --- enums (value + type) ---
${enums.map(valueAndType).join('\n')}

// --- functions (value only) ---
${functions.map((n) => `export declare const ${n}: typeof Ammo.${n};`).join('\n')}

// --- runtime helpers not present in the generated namespace (embind/emscripten) ---
${helpers.map((n) => `export declare const ${n}: any;`).join('\n')}
`;

writeFileSync(join(here, '../ammo/index.js'), js);
writeFileSync(join(here, '../ammo/index.d.ts'), dtsOut);
console.log(
  `Generated ammo/index.js + ammo/index.d.ts: ${classes.length} classes, ${enums.length} enums, ` +
    `${functions.length} functions, ${helpers.length} helpers.`,
);
